### ISSUE TITLE
Warn user when attachment posting is not allowed by server

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#105]
Currently Tentia silently fails

**Comment by jeena** [comment]
Hm I added some lines so it should show the user a error https://github.com/jeena/Tentia/blob/master/WebKit/scripts/helper/Core.js#L539 could you have a look in the Console.app what it says when it doesn't work? When I tested it from my tent.is account I got a 403 and I therefor I check for just that.

**Comment by poweruser82** [comment]
I tried now and the error message appeared.
Console says

```
29/12/12 14:38:39,626 Tentia[35489]: jsa<TimelineView>: ERROR: postMultipart (403)Forbidden (https://poweruser.tent.is/tent/posts): '{"error":"Attachments aren't currently allowed on the basic plan"}'
```

This morning nothing happened. This is what I found in Console around the time I tried to post the image:

```
29/12/12 08:58:02,498 Tentia[35489]: No error.
```

Maybe the check should be broader so it can handle network issue too.

**Comment by jeena** [comment]
Yes better network checks would be great but it is quite a  lot to do and I don't have the time for it right now, so this one check will have to do for right now.
