### ISSUE TITLE
Filter yt and vimeo links from posts and embed the vid below the text

### ISSUE THREAD

**Issue by Nygu** [jeena/Bungloo#113]

**Comment by poweruser82** [comment]
I don't like it very much, but if it has to be, let it be an HTML5 player. Better if it's the default (QT) player.

**Comment by jeena** [comment]
If then I wil just implement a thumbnail which will link to the youtube or vimeo video.

**Comment by bnb** [comment]
Jeena: Within the app, or in the user's browser?

**Comment by jeena** [comment]
The thumbnail will be shown within the app and when you click it it will open the users browser.
