### ISSUE TITLE
Empty conversation view

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#114]
Loading the conversation view for x-tents://jcook.cc?NrABgWggnAfi2E7brKr5Hg I get an empty conversation view.
Console says:

```
30/12/12 22:59:30,942 Tentia[35489]: jsa<ConversationView>: ERROR: getURL (0)error GET (https://tent.jcook.cc/posts/NrABgWggnAfi2E7brKr5Hg): ''
30/12/12 22:59:30,943 Tentia[35489]: js<ConversationView>: Conversation.js:45: SyntaxError: JSON Parse error: Unexpected EOF
```

It may be related to the Jacob's server move, but however a more descriptive error for the user would be nice.

**Comment by jeena** [comment]
Yes his server is fucked up, he will drop the database and start fresh, and it will fix his problems hopefully.

**Comment by poweruser82** [comment]
Another empty conversation starting from x-tents:/jeena.net/?khZfvmFtx7uVhb9eM5kN9w (https://poweruser.tent.is/posts/https%3A%2F%2Fjeena.net/khZfvmFtx7uVhb9eM5kN9w)

Console says:

```
27/01/13 15:43:24,525 Tentia[28704]: jsa<ConversationView>: ERROR: getURL (0)error GET (http://tent.jeena.net:3002/posts/khZfvmFtx7uVhb9eM5kN9w): ''
27/01/13 15:43:24,525 Tentia[28704]: js<ConversationView>: Conversation.js:45: SyntaxError: JSON Parse error: Unexpected EOF
```
