### ISSUE TITLE
Check for moved API root on startup

### ISSUE THREAD

**Issue by graue** [jeena/Bungloo#116]
When Tentia starts up it appears to load the API root from a file, and so if the API root has moved, the account is broken.

I believe the whole point of having API roots distinct from entities is that it should be seamless to move API roots. Therefore, it is wrong of Tentia to cache the API root; it should be looked up again from the entity URI when the app starts.

**Comment by jeena** [comment]
It is cached on OS X, but that cache is not implemented yet on Linux and what you describe should not happen there. Hm I will have to check that.

**Comment by poweruser82** [comment]
I had to restart Tentia to get @graue's posts to populate the conversation view.

**Comment by graue** [comment]
@poweruser82 Sounds like a different problem, maybe you should create a new issue for that? I'm referring to the fact that _your_ API root is saved in ~/.tentia.cfg and reused even after you restart.

**Comment by poweruser82** [comment]
API root cache should be removed altogether considering https://tent.io/blog/the-philosophy-of-tent

**Comment by jeena** [comment]
I removed the cache all together until all the issues can be resolved, if ever.
