### ISSUE TITLE
Stays open on Linux when all windows are closed

### ISSUE THREAD

**Issue by graue** [jeena/Bungloo#118]
If I only have the timeline window open in Tentia, and I close it with Ctrl-W, the process continues to run.

**Comment by jeena** [comment]
Hm are you sure you didn't have a "New Post" window open or something? I can't reproduce this behaviour.

**Comment by graue** [comment]
I'm sure. I can reproduce it every time, but it only happens if I close the window with Ctrl-W, not with Ctrl-Q or by clicking the 'x'.

Although if I click the 'x' or press Ctrl-Q while it is still loading parts of the timeline, it seems to segfault - unrelated bug, I guess. Ctrl-Q or clicking the 'x' works fine and quits cleanly if I have waited until everything is done loading after starting the app.

**Comment by jeena** [comment]
Ah ok now I understand it. It is like that by design. Ctrl-W only closes the window not the application. But I asume it is not like applications on Linux behave?

**Comment by graue** [comment]
Right, because then there is no way to reopen a window, quit or do anything with the application.

**Comment by jeena** [comment]
Hm I see ... then I would have to go through all windows check every one of them for visibility and if all are invisible then quit the application? Is that like it should behave?

**Comment by graue** [comment]
Sure. Your app somehow already does the right thing if I click the 'x' in one of the windows. (unless it's still loading)

**Comment by jeena** [comment]
Yeah but that is handled by Qt the show/hide thing is homemade.
