### ISSUE TITLE
Image posts doesn't show up in profile view

### ISSUE THREAD

**Issue by Zatnosk** [jeena/Bungloo#119]
Conversation view and the main stream loads images fine, but the posts are not loaded into the userspecific stream in their profile.
![Screen Shot 2013-01-06 at 19 16 23](https://f.cloud.github.com/assets/472541/46166/36ddb022-582d-11e2-9c6d-62350457e7e9.png)

**Comment by jeena** [comment]
This will be fixed in the next version.
