### ISSUE TITLE
can't login?

### ISSUE THREAD

**Issue by ghost** [jeena/Bungloo#12]
enter my tent.is entity, click login, loader spinning forever

**Comment by jeena** [comment]
Did you enter your full URL with https:// in front of it?

**Comment by ghost** [comment]
yeah i did...

not 10 minutes later i tried the same and it worked!

pbly tent-server was shortly down, issue closed )

**Comment by jeena** [comment]
I mark it as a duplicate of #8 too because this is really close related.
