### ISSUE TITLE
[Linux] Poor icon quality

### ISSUE THREAD

**Issue by bnb** [jeena/Bungloo#120]
On Ubuntu 12.10 the application icon is of extremely low quality. A larger icon would be appreciated.

**Comment by jeena** [comment]
Could you provide a screenshot? The icon is 512x512 px big so it should be sufficient.

**Comment by bnb** [comment]
![Screenshot from 2013-01-26 11:34:33](https://f.cloud.github.com/assets/502396/99945/9bbbf34c-67d6-11e2-8b05-67f1de573859.png)
There's a screenshot of the low quality icon.

**Comment by ghost** [comment]
how it looks now?

**Comment by jeena** [comment]
On my KDE it now looks much better so I assume this is fixed by https://github.com/jeena/Bungloo/commit/5d8e114b7cba638a3d002324a3613cb6d43041a8
