### ISSUE TITLE
[Linux] Post streaming in conversation view

### ISSUE THREAD

**Issue by bnb** [jeena/Bungloo#121]
It would be great if the conversation view (hover over a post > click the timestamp > the popup is conversation view) would stream posts. It was a few days ago that I noticed the app was lacking this functionality, so it obviously might have been implemented already.

**Comment by jeena** [comment]
Sadly there is no streaming API for tentd yet, according to the roadmap https://tent.io/blog/tent-roadmap it could be implemented in version 0.3 but I don't see anybody working on it yet. So I will close this issue because it is not possible right now to implement it.
