### ISSUE TITLE
[Linux] Can't post message with curly braces {}

### ISSUE THREAD

**Issue by graue** [jeena/Bungloo#122]
If I try to post `This is a {test message}`:

```
Traceback (most recent call last):
  File "/home/sf/code/forked/Tentia/Linux/Windows.py", line 358, in sendMessage
    self.app.controller.sendMessage(message)
  File "./Tentia.py", line 170, in sendMessage
    func = ("tentia_instance.sendNewMessage(\"" + text + "\", \"{}\", \"{}\", {}, {}, {});").format( in_reply_to_status_id, in_reply_to_entity, locationObject, imageFilePath, isPrivate)
KeyError: u'test message'
```

If I try to post `This is a {test message`:

```
Traceback (most recent call last):
  File "/home/sf/code/forked/Tentia/Linux/Windows.py", line 358, in sendMessage
    self.app.controller.sendMessage(message)
  File "./Tentia.py", line 170, in sendMessage
    func = ("tentia_instance.sendNewMessage(\"" + text + "\", \"{}\", \"{}\", {}, {}, {});").format( in_reply_to_status_id, in_reply_to_entity, locationObject, imageFilePath, isPrivate)
ValueError: unmatched '{' in format
```

May I suggest putting `text` in the call to `.format()` instead of sticking it in the format string directly?

**Comment by jeena** [comment]
Yes you may, the problem was that format doesn't work with utf8 :-( so this was my hot fix, didn't think about that possibility, will have to find another way, thanks for finding it.

**Comment by graue** [comment]
Does [this solution](http://stackoverflow.com/questions/3235386/python-using-format-on-a-unicode-escaped-string) (make the format string also be Unicode) fix it?

**Comment by jeena** [comment]
I don't use literals but a utf8 string in a variable if I'm not quite mistaken you cant do `u str_var`

**Comment by graue** [comment]
No, but there is the [`unicode()` constructor](http://docs.python.org/2/library/functions.html#unicode). What about `unicode(str_var)`?

**Comment by jeena** [comment]
Ah yes you're right I already use the unicode constructor I just didn't understand the solution but now I think I do `u"foo {} bar".format(unicode("über"))` I will test it

**Comment by jeena** [comment]
https://github.com/jeena/Tentia/commit/e75b9a867e1e851891f33d535405475243b676e9 should fix it.
