### ISSUE TITLE
Open Profile shortcut

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#123]
⌘P is usually the shortcut for the Print command.
⌘O would be good. ⌘⇧O would be even better.

**Comment by jeena** [comment]
Hm ok you're right, I'll change it.

**Comment by jeena** [comment]
But ⌘O is for open file isn't it?

**Comment by poweruser82** [comment]
⌘O is for Open. In document based apps it opens the Open dialog, otherwise it open/launch the selection.
If Tentia supported the navigation through keyboard, ⌘O would open the conversation view for the selected post.

**Comment by ePirat** [comment]
Actually the shortcut used _everywhere_ is ⌘U (Tweetbot, YoruFukuro, Osfoora, Twitter for Mac… do it like this)

**Comment by jeena** [comment]
U like for User? If that is standard then I think we should use it too.
