### ISSUE TITLE
Can't see attachment of not following entity

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#125]
If you look at a post with attachments of someone you don't follow (via profile, conversation or repost), Tentia can't get the attachment.
![Schermata 2013-01-15 alle 09 00 36](https://f.cloud.github.com/assets/325193/67133/d30187b2-5eea-11e2-9674-fe96be3723f1.png)

**Comment by jeena** [comment]
This should have fixed it self with Tent 0.3, if we ever bring back photos.
