### ISSUE TITLE
Unable to create new posts of any kind

### ISSUE THREAD

**Issue by thejayray** [jeena/Bungloo#14]
When attempting to create a new post, neither menu item works to compose a new status message. I have only just begun using the application, so I am at the point where I have only logged in, no other changes have been made.

**Comment by jeena** [comment]
So the New Post window doesn't open? But you see your timeline? Could you after trying that open the Console.app on your mac and post here what Tentia wrote into the console log?

**Comment by jeena** [comment]
I'm closing this bug because of lack of follow up and it seems to work for all others.
