### ISSUE TITLE
It's impossible to tell replies from non-replies.

### ISSUE THREAD

**Issue by Zatnosk** [jeena/Bungloo#140]
It's impossible to tell consistently whether a post is a reply to something. Replies doesn't require mentions at the start, even though it's default in Tentia.

**Comment by Zatnosk** [comment]
Suggestion: With the new conversation icon, it's possible to dim it or hide it if the post is singular, i.e. not part of a conversation.

**Comment by jeena** [comment]
I could hide it if it has no parent post, but that doesn't mean that it later on wouldn't have a child post. As long as we don't load older posts I could add the icon if a child or grandchild comes in but when we start implementing scroll to load older posts (which I really want to implement) this will break.
