### ISSUE TITLE
Window stays blank on startup

### ISSUE THREAD

**Issue by mwanji** [jeena/Bungloo#146]
Worked fine yesterday, but launched it today and the window just stayed blank. Here's what I got (Ubuntu 11.10):

![Screenshot at 2013-02-01 08:25:30](https://f.cloud.github.com/assets/58760/117386/78fa75a2-6c38-11e2-936b-9d70eb75d958.png)

**Comment by jeena** [comment]
I assume you tried to restart it already?

**Comment by mwanji** [comment]
Just tried starting it up again and it worked fine. Odd.

**Comment by jeena** [comment]
It is something weird with the hybernation, sometimes I get that behaviour too, will need to look into it.
