### ISSUE TITLE
Tentia caching issue

### ISSUE THREAD

**Issue by peakwinter** [jeena/Bungloo#147]
I switched my server yesterday to be on the same server as my ^citizenweb.is entity, as I am moving and my home server won't have internet access for a few days.

The current configuration is:
^citizenweb.is Server: http://tent.citizenweb.is:3000
^jcook.cc Server: http://tent.citizenweb.is:3001

I might be wrong, but this is an educated guess: It appears that if Tentia sees the server address (irrespective of the port number attached), it will automatically assume that the entity in question is the first one that it sees that uses that FQDN.

This problem can be remedied by clearing the cache. And it's not like it's a problem that will happen quite often. But if someone uses one server to host multiple entities on different ports, it might create unforeseen complications.

**Comment by jeena** [comment]
No tentia doesn't do that but what it does is if it sees a entity for the first time it caches the profie for ever (or untill you clear the cache). I assume that is what happened here. It should at least once a day clear the cache or something.

**Comment by jeena** [comment]
Cache is now disabled and I'm not sure if it will be enabled again because it causes so many problems.
