### ISSUE TITLE
tabs/spaces inconsistency

### ISSUE THREAD

**Issue by ghost** [jeena/Bungloo#148]
i was going through the code and found a shitload of tabs/spaces inconsistency in `.h` adn `.m` files. pls fix this

(sometimes 3-spaces "tabs")

**Comment by jeena** [comment]
The code is old any copy&pasted from different sources. If you have the time and would like to see that fixed then you will sadly need to do that on your own. I will, however, gladly include a pull request if you send one. Right now I have a ton of other more important stuff going on, renaming the app, implementing a search, etc., therefore I will close this with "wontfix".

**Comment by ghost** [comment]
that will be a lot of `++ --` on my part for nothing :)

**Comment by ghost** [comment]
rename the repo first
