### ISSUE TITLE
Rename Tentia to bungloo

### ISSUE THREAD

**Issue by jeena** [jeena/Bungloo#149]

**Comment by riccard0** [comment]
Bungloo?
Are you really sure?
…
Bungloo…
…
Maybe it isn’t that bad…
Maybe… ;-)

**Comment by jeena** [comment]
Hehe it is the best one I found in a list of 35 proposals ;) And it will be written in lowercase, bungloo, not Bungloo.

**Comment by riccard0** [comment]
Why the lowercase? I mean, that’s OK for a logo/wordmark, but in running text?

Il giorno 10/feb/2013, alle ore 22.53, Jeena Paradies ha scritto:

**Comment by jeena** [comment]
Hm yeah perhaps you're right, I will call it bungloo as a logo/wordmark but in running text I wil write Bungloo, good idea.
