### ISSUE TITLE
Reduce post-type and profile-type permissions

### ISSUE THREAD

**Issue by seanmonstar** [jeena/Bungloo#159]
I just re-authed Bugloo, and noticed it's still asking for "all" and "all".

**Comment by seanmonstar** [comment]
Just noticed this again as I grabbed Bungloo for Windows (nice job, btw!). So, uh, bump?

**Comment by jeena** [comment]
Yes yes, I was so busy with the windows version that I didn't even think about the issues here but it will be changed in one of the next versions.

**Comment by jeena** [comment]
Ah this has been done a couple of months ago actually.
