### ISSUE TITLE
OS X Notification

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#16]
Tentia should show a notification in OS X Mountain Lion Notification Center on mentions (or for each post, if user wants).
The implementation could use Growl framework so it would be available to older OS users too.

Notification text could show the status text.

**Comment by poweruser82** [comment]
Now that we have a conversation view, clicking on a notification of a post could show the conversation of that post.

**Comment by jeena** [comment]
Hehe actually it was like that at first and I have it still commented out in the code ;) But it didn't update the unread mentions so my quick fix was just to show them instead. But yes it is a good point, I will try to find some way to do it that way.

**Comment by jeena** [comment]
I opened a new bug for that #30
