### ISSUE TITLE
posts-count question

### ISSUE THREAD

**Issue by ghost** [jeena/Bungloo#162]
i'm thinking if posts-count should only have statuses, reposts and photos, or overall count minus deleted posts?

**Comment by ghost** [comment]
and prbly amount of supported by an app posts somewhere separate

**Comment by poweruser82** [comment]
I think bungloo shouldn't fetch posts it doesn't support at all (and ask permission for them only)

**Comment by ghost** [comment]
it's not about fetching posts, only `count`-s

**Comment by poweruser82** [comment]
If you can't fetch them, you can't count them.

**Comment by ghost** [comment]
on the contrary, there is an API for counts only: 

``` sh
curl https://poweruser.tent.is/tent/posts/count?post_types=https%3A%2F%2Ftent.io%2Ftypes%2Fpost%2Fstatus%2Fv0.1.0,https%3A%2F%2Ftent.io%2Ftypes%2Fpost%2Frepost%2Fv0.1.0
```

or

``` sh
curl --head https://poweruser.tent.is/tent/posts/?post_types=https%3A%2F%2Ftent.io%2Ftypes%2Fpost%2Fstatus%2Fv0.1.0,https%3A%2F%2Ftent.io%2Ftypes%2Fpost%2Frepost%2Fv0.1.0
```

**Comment by poweruser82** [comment]
Ok, it makes sense.

**Comment by jeena** [comment]
Right not it is repost + staus + photo: https://github.com/jeena/Bungloo/blob/master/WebKit/scripts/controller/Profile.js#L308
