### ISSUE TITLE
Enlarge map preview

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#164]
![Schermata 2013-02-18 alle 19 31 36](https://f.cloud.github.com/assets/325193/168371/895e87b6-79f9-11e2-871e-0868dc746157.png)

**Comment by riccard0** [comment]
+1

Il giorno 18/feb/2013, alle ore 19.32, poweruser82 ha scritto:

**Comment by jeena** [comment]
But which width should I take? I have to use a static width, I can't use 100% and everybody has a different width so if I want to have it flexible I'd need to use some JS thingy which would slow down the scrolling down even more.

I could try to use 640px and then overflow auto, but things could get messy.

**Comment by poweruser82** [comment]
``` javascript
$('p.message').width()
```

**Comment by jeena** [comment]
Hm very nice idea!
