### ISSUE TITLE
Conversation view icon

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#167]
The conversation view icon is not as crisp as the other icons.

**Comment by jeena** [comment]
Yes I know, that is because it is the only one I did myself in Photoshop because I couldn't find one in that size. If you somebody can fix that it would be much appreciated.

**Comment by poweruser82** [comment]
PNG ![conversation](https://f.cloud.github.com/assets/325193/171488/75a5a0f2-7a9d-11e2-9ae4-6ca9b1dac6ff.png)
SVG http://cl.ly/0o0y0V2m0s1J

**Comment by jeena** [comment]
Very nice! I will add it to the next version, thanks!
