### ISSUE TITLE
post is repeated if reposted between the refreshings

### ISSUE THREAD

**Issue by ghost** [jeena/Bungloo#169]
![Screen-Shot-2013-02-19-at-20 51 53](https://f.cloud.github.com/assets/3467051/173025/c77b8ab4-7ace-11e2-905a-4a56a6d5aff5.jpg)

https://uns0b.tent.is/posts/2xA_vdDaLWq886c8g3kK2A

**Comment by jeena** [comment]
I hope this has fixed itself now with Tent 0.3
