### ISSUE TITLE
pbly should not be able to repost my own posts

### ISSUE THREAD

**Issue by ghost** [jeena/Bungloo#170]

**Comment by jeena** [comment]
The question is, why not?

**Comment by ghost** [comment]
don't see any use case for that, but it's up to you

**Comment by jeena** [comment]
One use would be if you feel that one of your posts didn't get enough exposure and you want to bump it to the top :)

**Comment by ghost** [comment]
in current flow situation, sure, can be.

but if some structure will be added, like in fb/frf/forum posts, than after you reply to your own post it bumps up the parent post to the top.

also, repost's moto is "spread", not "repeat" :)
