### ISSUE TITLE
can't see my own profile

### ISSUE THREAD

**Issue by ghost** [jeena/Bungloo#173]
...and "follow" myself?
also tried the current `master` branch, the same.

![Screen Shot 2013-02-20 at 18 59 49](https://f.cloud.github.com/assets/3467051/177037/f1240e0e-7b87-11e2-94c6-60ff8a97062b.png)

**Comment by jeena** [comment]
Looks like it doesn't load your profile json for some reason.

**Comment by Nygu** [comment]
I'm having the same problem. ;-)

**Comment by jeena** [comment]
I changed a bit in the profile code, could you test if the problem is still there?

**Comment by ghost** [comment]
nope, still the same

**Comment by jeena** [comment]
Ah but you tested with the normal OS X version 1.1.0 which is out there not with a newly downloaded Linux version which would have implemented the changes I assume?

**Comment by ghost** [comment]
ah, yes, good call, now i see me.
