### ISSUE TITLE
New Post window doesn't show scrollbar when the text doesn't fit

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#175]

**Comment by jeena** [comment]
Ah you're right, on Linux it does but on OS X it doesn't

**Comment by jeena** [comment]
Hm I'd need to use a NSTextView http://stackoverflow.com/questions/10420236/how-to-add-vertical-scrollbar-to-nstextfield

I tried that once and I got quite many problems, I will need to try it again.

**Comment by poweruser82** [comment]
Or you could save your time and replace everything with a WebView so in the future you can implement entity autocompletion or other cool tricks the web way

**Comment by jeena** [comment]
The problem with a webview there is that if I need to open a menu which is bigger then the window then it will not be visible. On the other side, it would take the same amount of work to implement the menu in obj-c/python then it would take to make it possible to open that menu from JavaScript.

I will think about that, perhaps it it is really good idea.

**Comment by jeena** [comment]
This is fixed in 2.0 because it is now a html textarea.
