### ISSUE TITLE
how to handle non-square avatars?

### ISSUE THREAD

**Issue by ghost** [jeena/Bungloo#179]
square crop or `max-height:50px; max-width:50px;`?

**Comment by ghost** [comment]
ehm, i think, should be constant (or maximal) height and max-width, otherwise it may at some point be like 20 posts each with one line of text and 300px of longcat avatars near them. it will be like in old forums

**Comment by ghost** [comment]
i'll send a pull-req really quick

**Comment by jeena** [comment]
Hm, I'm not sure I like it, I want them to always have the same width and to be able to vary in height a little. If we have different widths then it will look hideous.

**Comment by ghost** [comment]
no problem, i'll close that pull-req
