### ISSUE TITLE
[Linux] missing module "bungloo"

### ISSUE THREAD

**Issue by vinzv** [jeena/Bungloo#183]
Running Linux/Bungloo.py gives me this error:

Traceback (most recent call last):
  File "Linux/Bungloo.py", line 9, in <module>
    from bungloo import Windows, Helper
ImportError: No module named bungloo

**Comment by jeena** [comment]
Hm I assume it has to do with the changes yesterday, I will try to have a look at it tonight after work.

**Comment by jeena** [comment]
Fixed by https://github.com/jeena/Bungloo/commit/1568c19db9a5ebbe858515544c11e420d9e04ba5
