### ISSUE TITLE
[Linux] Trying to deploy/install failed

### ISSUE THREAD

**Issue by vinzv** [jeena/Bungloo#184]
I tried to deploy (which worked as far I can see) and install. I ran into this error:

[vinz@calvin build]$ sudo python setup.py install
running install
running build
running build_py
running build_scripts
running install_lib
byte-compiling /usr/lib/python3.3/site-packages/bungloo/Helper.py to Helper.cpython-33.pyc
  File "/usr/lib/python3.3/site-packages/bungloo/Helper.py", line 24
    print str(message) + " on line: " + str(lineNumber) + " Source: " + str(sourceId)
            ^
SyntaxError: invalid syntax

running install_scripts
changing mode of /usr/bin/bungloo to 755
running install_egg_info
Removing /usr/lib/python3.3/site-packages/bungloo-0.1-py3.3.egg-info
Writing /usr/lib/python3.3/site-packages/bungloo-0.1-py3.3.egg-info

**Comment by jeena** [comment]
Ah hehe hm I have no idea, it was @ckruse who implemented that I will need to have a look at it first, until then just run it like it was before with Bungloo.py

**Comment by ckruse** [comment]
No, this is Bungloo issue, not a deployment issue. You are using python3 for executing the setup.py, but Bungloo is not python3 compatible. You have to either run `./setup.py install` (which calls `/usr/bin/env python2`) or you have to call the `setup.py` manually with a python2 version

**Comment by jeena** [comment]
Ah thanks for clearing that up.

**Comment by vinzv** [comment]
Well, now I get the following:
$ sudo ./Linux/setup.py install
running install
running build
running build_py
error: package directory 'bungloo' does not exist

**Comment by ckruse** [comment]
Can you have a look in Linux/build, what files and directories are
there? Does a Linux/build/bungloo/**init**.py exist?

**Comment by renfrowk** [comment]
I'm getting the same error message as vinzv. "error: package directory 'bungloo' does not exist".

I see no such Linux/build directory.

**Comment by jeena** [comment]
I assume you need to run the deploy.sh script first because Bungloos file structure isn't compatible with the setup.py thingy. the deploy.sh copies all the files (also the ones shared with the OS X version) into a structure which setup.py then can use to install.

**Comment by renfrowk** [comment]
Ah, after running deploy.sh I still receive the same error when running install.py

```
$ sudo ./setup.py install
running install
running build
running build_py
error: package directory 'bungloo' does not exist
```

@ckruse, yes, Linux/build/bungloo/**init**.py exists.

**Comment by jeena** [comment]
This is how one is supposed to do it:

```
git clone git://github.com/jeena/Bungloo.git
cd Bungloo/Linux
./deploy.sh
cd build
sudo python setup.py install
```

So you need to be in the build directory. But the thing is, I want to change it and make it less complicated, actually I'd just like to have a deb package or something which would install all the stuff needed to run too.

**Comment by jeena** [comment]
One can use the deb package now.
