### ISSUE TITLE
Conversation view posts order

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#188]
Sometimes conversation view shows posts in the wrong chronological order:
![Schermata 2013-03-04 alle 10 28 14](https://f.cloud.github.com/assets/325193/215913/07c9d790-84ae-11e2-8d4d-042cf134f5f6.png)

**Comment by jeena** [comment]
That happens when there are two answers to one post, bungloo just does body.insertBefore(new_post, parent_post) and then it depends on the time the servers need to respond to the request, that determines the sorting. But yeah it would be cool if we could fix that.

**Comment by jeena** [comment]
I'd say this is now kind of fixed with 2.0 and the new conversation view and the fact that everything comes from the same server.
