### ISSUE TITLE
Cookie space

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#189]
Bungloo is sharing the Safari cookie space, so it sends cookies to a server if you have visited it.

Example: If you are logged in campr.me via Safari and open your campr profile from Bungloo you get your timeline instead of just your posts. This is because at the moment campr uses a cookie for authentication and bungloo sends that cookie when it loads the profile.

In general, this could be a privacy and security problem.

**Comment by dblugeon** [comment]
Hi
, I try reproduce your issue case, but I don't see my campr timeline through Bungloo. 
My try is under os X 10.8.3, safari 6.0.4.
Maybe, I didn't understand your use case.

**Comment by poweruser82** [comment]
Same OS X and Safari.
My Bungloo is logged in with my tent.is entity.
This is what I get in Bungloo if I open my profile while I'm logged in Safari with my campr.me entity:
![loggedin](https://f.cloud.github.com/assets/325193/463825/693488a2-b5a2-11e2-9f52-0eb43c706452.png)

This is instead what I get in the same scenario but logged out from campr.me:
![loggedout](https://f.cloud.github.com/assets/325193/463828/aabb4efa-b5a2-11e2-83e4-0a227019be1c.png)

Step to reproduce the problem:
1. log in bungloo with a tent.is entity
2. log in to campr.me in safari with a campr.me entity
3. open the campr.me entity in bungloo (⌘U)
4. see what you get :)
5. log out from campr.me in safari
6. open the campr.me entity in bungloo again (⌘U)
7. see you get a different result :)

**Comment by dblugeon** [comment]
Thanks @poweruser82, and arrghghh!!!!!. 
I success to reproduce this. Very strange, before logout and clean cookie, I didn't have this issue.

**Comment by dblugeon** [comment]
After search, I think the best way to solve this issue is use this http://developer.apple.com/library/mac/#documentation/Cocoa/Reference/Foundation/Classes/NSHTTPCookieStorage_Class/DeprecationAppendix/AppendixADeprecatedAPI.html#//apple_ref/occ/instm/NSHTTPCookieStorage/initWithStorageLocation:  
But to use this, we need drop support Mac os X 10.5 or use macro and 10.5 will have again the problem but no 10.6 or  above.

**Comment by poweruser82** [comment]
I just found [this](http://stackoverflow.com/questions/364219/how-can-i-have-multiple-instances-of-webkit-without-sharing-cookies), check the first 2 answers.
