### ISSUE TITLE
Add "back" button

### ISSUE THREAD

**Issue by peakwinter** [jeena/Bungloo#191]
With the new one-window interface, sometimes I can click someone's post, then go to their profile, then see what followers they have, etc etc. A back button might be nice if I wanted to go back to the last thing I saw, whereas before I just had to look at one of the other windows I had open.

**Comment by poweruser82** [comment]
For me It is even more useful for conversation view. If it has a shortcut I can bind them to a (swipe) gesture.

**Comment by jeena** [comment]
The trouble I have with it is that a back button needs a history and I can't provide something like that with the structure like it is now where there are just views which get reused all the time.
