### ISSUE TITLE
Add shortcuts to cycle among views

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#192]
This way I can map them to swipe gestures

**Comment by bnb** [comment]
Very good idea. `Ctrl` + `+` for forward, and `Ctrl` + `-` for backward?

**Comment by jeena** [comment]
I'd like to use + and - for resizing the font size in the future some 
time.

**Comment by poweruser82** [comment]
OS X current convention is to use `⌃⇥` and `⌃⇧⇥`.
Firefox uses `⌘⌥→` and `⌘⌥←`
Coda and others use `⌘[` and `⌘]` or `⌘{` and `⌘}` but they aren't easy on Italian keyboard layout.
`⌘<` and `⌘>` (I think US layout uses `⌘`` but I'm not sure) are reserved to cycle among multiple windows.

**Comment by jeena** [comment]
for now it is Cmd/Ctrl - 6 to go to the next one.

**Comment by poweruser82** [comment]
I don't like that shortcut. And there is no backward scroll.
