### ISSUE TITLE
Add "mine" class to owned posts

### ISSUE THREAD

**Issue by sfcgeorge** [jeena/Bungloo#198]
So that themes can style tweets by the account owner differently, it would be nice to have a class added to those posts. Something like "mine" or "owned".

**Comment by jeena** [comment]
They are not called "Tweets" but "Posts" ;) Otherwise I agree and will 
add that.

**Comment by sfcgeorge** [comment]
> .< Whoops! Tent is obviously the superior service, I will repent. And thanks :)
