### ISSUE TITLE
Add name of tab to body class.

### ISSUE THREAD

**Issue by sfcgeorge** [jeena/Bungloo#199]
E.g. <body class="conversation"> or "timeline"

This would enable me to add a 'back' bar in a CSS theme for profiles and conversations, and could possibly be useful in other ways. Currently the only way of knowing which tab is selected is with a selector like `img[src$="active.png"]` which is fiddly and only works for selecting that image, not parent elements.

**Comment by jeena** [comment]
it is now `body-timeline` and so on.

**Comment by jeena** [comment]
fixed by https://github.com/jeena/Bungloo/commit/cbed4eae9c883f64accf45d8e31f2aa935194a20
