### ISSUE TITLE
Repost button should be hidden on own statuses

### ISSUE THREAD

**Issue by sfcgeorge** [jeena/Bungloo#200]
This seems more like a Tent bug. Why would you want to repost your own status? Very odd. I don't know if you should keep it enabled in the app because Tent allows it, or disable it because it's odd.

**Comment by jeena** [comment]
The question is, why should either the protocol or the app prevent you to repost your own post if you want to?

**Comment by sfcgeorge** [comment]
How do reposts work on Tent? I'm guessing they are like a brand new post. On Twitter a repost never shows up on a timeline more than once, so reposting wouldn't make any sense as it would have no effect. I don't know, it's not a big issue really.

**Comment by jeena** [comment]
Yes in Tent a repost is a new post with the type "repost" and clients are free how they want to visualize it. Bungloo does it kind of the the Twitter way but only if that post is already visible. If it is not visible anymore then it puts it on top of your timeline again. All the other apps show it every time on top of your Timeline as a copy.

So reposting your own post can be used to put it on top of peoples Timelines again (right now) and therefore I won't change the behaviour for now.

**Comment by sfcgeorge** [comment]
Makes sense, sounds like Bungaloo does it the best way :) Could be abused by spammy people, but then I guess you just wouldn't follow them.
