### ISSUE TITLE
Search field

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#201]
Change the placeholder text to `Search…` (i.e. without the space and with the ellipses).
Add the lens icon inside the field.
Make the search to start automatically when the user start typing (or after 3 characters)

**Comment by bnb** [comment]
Do you mean have it start searching automatically when the user starts typing anywhere, or just in the search page? Either way, it's an interesting feature.

**Comment by poweruser82** [comment]
Just when the focus is on the search field. Otherwise a search button should be required.

**Comment by jeena** [comment]
Afaik there must be a space because otherwise the ellipses would indicate that the word will continue.

**Comment by jeena** [comment]
The thing is, qt on OS X already adds a icon inside the field, it is a bit sad that it doesn't do that on Windows and Linux.

I will not change the search to automatically because I don't want to add unnecessary load to the skate.io server so they feel the need to revoke my API key ;)

**Comment by poweruser82** [comment]
Cocoa OS X doesn't show the icon.

On OS X ellipses in a menu item's title mean that further user action is required after you choose the item.
In this case the current implementation the action could be press enter key. But it is not a strong argument.

Standard OS X search field no longer show any placeholder text, but it always shows the icon and the search starts as you type.
Two exception I found: Safari Smart Search Field
![Schermata 2013-04-09 alle 18 25 19](https://f.cloud.github.com/assets/325193/357949/1d1ef580-a132-11e2-84e1-fdc4cf40d612.png)
and Messages sidebar
![Schermata 2013-04-09 alle 18 25 45](https://f.cloud.github.com/assets/325193/357951/32055304-a132-11e2-9154-57b9a70f7f57.png)
Neither of them has ellipses.
So maybe it may be better to have no ellipses at all.

**Comment by jeena** [comment]
Yes you're right, I will remove the elipses.
