### ISSUE TITLE
Apparent double repost

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#202]
![Schermata 2013-03-31 alle 22 36 55](https://f.cloud.github.com/assets/325193/322390/43f6be6e-9a47-11e2-87d1-a48719315096.png)
Sometimes it looks like you have reposted twice. But on tent.is there is only a repost and the repost id is the same.
![Schermata 2013-03-31 alle 23 09 50](https://f.cloud.github.com/assets/325193/322393/639dfd4a-9a47-11e2-978b-6eb296048eec.png)

**Comment by jeena** [comment]
Yeah I saw that too, I'm not sure why that happens yet, will need to look into it.
