### ISSUE TITLE
Highlight # in hashtags

### ISSUE THREAD

**Issue by Cacauu** [jeena/Bungloo#204]
I think it'd be nice if Bungloo would also highlight the # in hashtags and not just the rest of the tag. In my opinion that'd my hashtags better visible and easier to realize that the # actually belongs to the tag.

**Comment by bnb** [comment]
+1. This is something that always annoys me. Thankfully, Bungloo makes the other area where this usually happens moot, since it replaces ^mentions with the user's name.
