### ISSUE TITLE
Reposts not visible in Mentions

### ISSUE THREAD

**Issue by Zatnosk** [jeena/Bungloo#206]
Reposts add to the unseen mentions counter, although they're not shown in the Mentions view.

**Comment by bnb** [comment]
Do we really want to see reposts of our posts (if I understand you correctly) in our mentions feed? It feels like it clutters it all up to me. Maybe have a separate (or replace mentions with) "Interactions" feed, where you get all mentions, reposts, follows, etc., similar to how Twitter does it.
