### ISSUE TITLE
[Windows] Avatars of most entities don't show up

### ISSUE THREAD

**Issue by bnb** [jeena/Bungloo#207]
In the build of Bungloo for Windows that I've got, the majority of avatars don't show up. There are some, like ^shawnj.tent.is's, ^daniel.tent.is's, ^mkr.tent.is's, and ^zatnosk.tent.is's that always show up, but 90% of the other avatars don't.

**Comment by jeena** [comment]
afaik this has been resolved with a reinstall, closing it.
