### ISSUE TITLE
Options for reply styles

### ISSUE THREAD

**Issue by bnb** [jeena/Bungloo#208]
Some customization in the form of how replies are automatically formatted would be nice. I do like the current way with the /cc when there are multiple mentions, but I don't like how it's highlighted automatically. Besides that more specific problem, it would just be nice to have some alternatives.

**Comment by poweruser82** [comment]
I like how it is. An alternative would be to don't select the /cc part but leave the caret where the selection starts now.

**Comment by jeena** [comment]
This is only a workaround until I get to change the UI for new posts so you could mention people who aren't even in the text. It is easier to unselect then to select the exact text so I will not change it for now.
