### ISSUE TITLE
Videos don't work (Flash/HTML5)

### ISSUE THREAD

**Issue by bnb** [jeena/Bungloo#209]
Both vimeo and YouTube videos don't work in Bungloo for me--I didn't have Flash player installed before, but even after I installed it (and restarted Bungloo) they still don't work.

**Comment by bnb** [comment]
Update: I believe this is related to issue #207. It seems the majority of images/media don't show up. I've noticed that embedded images from sites like Imgur display broken images as well.

**Comment by jeena** [comment]
As far as I know this was resolved through a reinstall, closing it.
