### ISSUE TITLE
Usability: when forgotten - automatically add http:// on login

### ISSUE THREAD

**Issue by logsol** [jeena/Bungloo#213]
instead of promting an error that http:// https:// is missing, it could be added automatically

**Comment by bnb** [comment]
I would suggest https:// over http://, as I think it's required in 0.3 to make situations like this simpler. If it's not, then we should have a popup that asks whether the user wants to use http:// or https:// if neither protocol is used.

**Comment by poweruser82** [comment]
It could automatically try with https first (it's not required for entities, just for servers) and if it fails it could try with http giving a little (inline) warning.
