### ISSUE TITLE
Startup takes ~45s-1m [Windows]

### ISSUE THREAD

**Issue by seanmonstar** [jeena/Bungloo#214]
The Bungloo window shows up, and shows a tent picture and my avatar, and then takes about a minute to show anything more. I thought maybe it broke, but it just consistently takes a while start up.

**Comment by jeena** [comment]
Hm yeah it is because it has to get 400+ posts at startup and it seems that the tent.is server is not as fast as my own. I want to implement load on scroll then I could just load 20 at startup but it will take some time until I get to the implementation of that.

**Comment by seanmonstar** [comment]
I understand, I can see slow fetch times in splatmonstar also. Do you cache posts locally? Could you show them upon startup?

Or perhaps just a spinner and status text "Fetching posts from your server..." would let users know it's doing something.

Extra points if the status text changes like in Gmail, after a time limit (say 10 seconds) the text changes "Still fetching, sorry it's taking so long..."

**Comment by jeena** [comment]
Hm yeah, I have had implemented cache but it fucked up too much stuff so I didn't want to put in more time. I will try to add that spinner.

**Comment by poweruser82** [comment]
#81

**Comment by jeena** [comment]
fixed with https://github.com/jeena/Bungloo/commit/b210e6ee323daa24246445c41afbaa5202cd34ee
