### ISSUE TITLE
Ability to remove mentions from a "reply-all"

### ISSUE THREAD

**Issue by mplorentz** [jeena/Bungloo#215]
Sometimes I want to reply-all to a post but remove a few of the mentioned entities. Right now if you remove an entity from your post text the person will still be mentioned in the json. (at least I think that's how it works behind the scenes)

**Comment by jeena** [comment]
Not quite, only the person who wrote the original post stays in the 
mentions array even if you remove her from the text because you are 
replying to a specific post and otherwise it wouldn't be possible to 
still have the relation to that post. That is like the protocol works.

**Comment by mplorentz** [comment]
Ok, my bad. I assumed that since I was getting mentioned when I replied-all to myself it was doing that for other entities as well. Thanks for the quick response!
