### ISSUE TITLE
Bungloo.exe.log could not be opened

### ISSUE THREAD

**Issue by pc1oad1etter** [jeena/Bungloo#238]
Just installed for the first time.  I'm on Windows 7 and I got this permission error.  I think a similar error happens during installation (maybe it failed to write the file) and it definitely happens each time I try to launch the app.
![screenclip](https://f.cloud.github.com/assets/404563/732088/cf12a988-e27a-11e2-929f-613e23d1cddf.png)

**Comment by jeena** [comment]
Does it really happen when you try to open the app? For me it happens when I close the app.

**Comment by pc1oad1etter** [comment]
Yes.  The process ends as soon as a click through the dialog.

**Comment by pc1oad1etter** [comment]
Thanks! I'll try to remember to check this out after the binary is updated.
