### ISSUE TITLE
OAuth flow in Arch/XFCE

### ISSUE THREAD

**Issue by iangreenleaf** [jeena/Bungloo#246]
Documenting my attempts to get the new Bungloo running on Arch Linux and XFCE.

Right now I need the browser to send the `bungloo://` URL back to the Bungloo process so it can finish authenticating.

I added this line to `~/.local/share/applications/mimeapps.list`:

```
x-scheme-handler/bungloo=bungloo.desktop;
```

This got Firefox to at least open up a "Choose application to launch this link" dialog (previously it just failed to load the page). But the dialog has an empty list instead of suggesting that I use Bungloo. I've tried manually adding both `/usr/share/applications/bungloo.desktop` and `/usr/bin/bungloo`, and neither of them seems to do the trick.

What should I try next?

References:
- https://wiki.archlinux.org/index.php/Default_Applications
- http://unix.stackexchange.com/questions/38650/adding-bindings-for-ed2k-links-with-xdg-open

**Comment by jeena** [comment]
Hm good question. I had the problem in Firefox on Ubuntu and chosing /usr/bin/bungloo did the trick.

**Comment by iangreenleaf** [comment]
How odd - one restart later and choosing `/usr/bin/bungloo` now works. I may have had something weird happening in my environment. Wish I could get it to present Bungloo as a choice unprompted, but at least it's working now! Would probably be good to have `setup.py` or the `PKGBUILD` add the protocol handler automatically. I think the way I mentioned is the most future-compatible.

**Comment by jeena** [comment]
Normally it should be enough to have the MimeType in the bungloo.desktop file, at least that is what makes if work under Gnome (and I think KDE too but haven't tested that yet).
