### ISSUE TITLE
Clearing OS X notifications

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#31]
If you click on a notification, it should be removed from notification center.
If you open the mentions view (considering the current implementation), all notifications should be cleared.

**Comment by jeena** [comment]
Hm ok I even found a API for that (http://stackoverflow.com/questions/12113300/nsusernotificationcenter-dismiss-notification), but it is undocumented so it could change in the future and if I would some time in the future want to get Tentia into the AppStore then I would have to remove it. But for now I added that.
