### ISSUE TITLE
Missing repost

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#34]
In my Timeline (http://cl.ly/image/3c06462p173G) a repost is missing.
It is available on Zelten (http://cl.ly/image/3L2m3O0g1j3E) and Tent.is (http://cl.ly/image/2S0q1E0J2R2I)
Repost id: http://jeena.net/l52fna
Original post: https://kevinkleinman.tent.is/ps7u4n
If it could be useful, I don't follow https://kevinkleinman.tent.is

**Comment by jeena** [comment]
Reposts are not implemented yet, they will be implemented a bit later.

**Comment by jeena** [comment]
Ok I will close this as a duplicate of #48
