### ISSUE TITLE
Missing posts in conversation view

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#35]
Loading conversation view from two posts belonging to the same conversation shows different results:
http://cl.ly/image/0E171V3X3j3f
http://cl.ly/image/0M3U2X1G121N
(I'm not following Kleinmann so his post shouldn't be on "my" tent server)

**Comment by jeena** [comment]
Yeah that is the case, your server can not know about what conversation goes on later if it doesn't follow Kleinmann and it can not ask anyone else either because the decentralized way Tent works. I cant't see any solution to the problem yet.

**Comment by poweruser82** [comment]
So the Kleinman posts I see come from a request to Daniel's server?

**Comment by jeena** [comment]
Yes, sadly my attempts to get it via the /followings method didn't work at all so I just decided to go the easy way and get it from the entities server directly.

**Comment by poweruser82** [comment]
Posts retrieval works only backward. I think because the post type only contains infos about the parent post and not about children.
I'm thinking the problem is that Tent protocol lacks an API to query a server every post that is a children of a given one (obviously with the proper privacy constraints).

**Comment by jeena** [comment]
Yes, that is because if the server isn't following a given entity it is not notified about posts that are children of a given one.

**Comment by jeena** [comment]
It seems to me not possible to implement with the current protocol so I close this issue.
