### ISSUE TITLE
Allow following and unfollowing profiles

### ISSUE THREAD

**Issue by tjreo** [jeena/Bungloo#49]
When people repost, I look closely because these are people with similar interests. Many times, I want to follow that person. I'd like the ability to perform that action within Tentia.

I'd also like the ability to unfollow someone from within Tentia.

It seems to me that there would be a profile pop-up similar to Zelten, but probably on-click, where this could be done.

**Comment by jeena** [comment]
Yes this is planed in the nearer future after I got some version in Linux working, so I can develop for both with the same JS-code.
