### ISSUE TITLE
The importance of clicking on a post

### ISSUE THREAD

**Issue by tjreo** [jeena/Bungloo#50]
When I click on a post, it means that it is important in some way and that I want to keep my eye on it even if I scroll.

I expect that when I click on a post, it will highlight or change color in some way. I also expect it to stay highlighted until I click on something else.

Right now, there is no way to make this happen and the only color changes are on hover.

**Comment by jeena** [comment]
Hm this is a very special request, I think the best way to deal with stuff like that would be to allow the user to write small plugins in JavaScript and CSS. This is already kind of implemented but not tested yet, I will try to make it happen as soon as possible.

**Comment by riccard0** [comment]
Another way would be to just open the conversation view, even if there is no conversation. Doing so, the post will be highlighted in its own window, remaining visible even if one scrolls past it in the main window.

**Comment by jeena** [comment]
Yeah but if he wants to highlight more then one then it wouldn't work because there is only one conversation view.

**Comment by riccard0** [comment]
tjreo: “I also expect it to stay highlighted until I click on something else”.
So no multiple selection was asked.
And anyway I don’t think multiple selection would be in line with the focused nature of a client like Tentia.

**Comment by poweruser82** [comment]
@jeena this will be solved with multiple conversation views

**Comment by jeena** [comment]
I've implemented it through a plugin and am closing this one. See https://github.com/jeena/Tentia/wiki/Plugins
