### ISSUE TITLE
Tentia lost my post

### ISSUE THREAD

**Issue by tjreo** [jeena/Bungloo#53]
I just posted a reply using Tentia. It has not shown up in the timeline in Tentia nor has it shown up in Zelten or Tent.is.  It appears to be lost.

THIS IS A HUGE, MAJOR, EARTH-SHATTERING DEAL!!! 

Sorry for screaming but this problem is as big as they come. Do not allow a user to lose their content. Nothing is more important than that. I believe this is the second time today this has happened to me. The first time was a test and I moved on without thinking but the post never arrived in the timeline.

If there is anything I can do to help look into this, please let me know. And a debug window in Tentia showing all posts the user submitted would really help ease my mind during testing. As of now, I can't trust the app which means it won't get used.

**Comment by jeena** [comment]
I think this was a bug where if you had a new line in your post then it would just crash and never let you know about it. This is fixed in the version I released yesterday, please "Check for update ..." install the new version and test again.
