### ISSUE TITLE
Private posts aren't marked as private

### ISSUE THREAD

**Issue by tjreo** [jeena/Bungloo#54]
Tentia is showing private posts just fine but they aren't labeled as private. Makes me do a double-take every time I see one of those.

**Comment by jeena** [comment]
Ah hm ok, I never used private posts because it is not implemented in Tentia to send them and the only one private post I ever got was not visible in Tentia back then (I don't know why it was a long time ago) so I never investigated it. But yes they need some marker that they are private I agree.
