### ISSUE TITLE
Re-authentication doesn't work after revoking authentication.

### ISSUE THREAD

**Issue by darishante** [jeena/Bungloo#56]
Tried to use tentia to access my private server at https://foo, but the server had problems and it wouldn't work. Tried to point tentia back at https://dare.tent.is, but didn't get that working either. Removed nu.jabs.apps.tentia.plist and nu.jabs.apps.tentia.plist.lockfile, tried again, didn't work. Revoked authentication for tentia in https://dare.tent.is/ account settings, tried again. Keep getting error message "Authentication error - Could not find profile for: https://dare.tent.is/"

Observed on MacOS 10.7.5

**Comment by darishante** [comment]
oh, and tentia version 0.2.2

**Comment by jeena** [comment]
Why did you close this issue? I know about the problems, just didn't have time to look into it. The workaround I use is File -> Logout, restart Tentia, login works like expected again.

**Comment by darishante** [comment]
Um, closed by accident, didn't mean to.

Tried to log on to https://dare.tent.is/, failed, entered File -> Logout, quit Tentia, restarted. Still getting the error "Authentication Error - Could not find profile: https://dare.tent.is/"

**Comment by jeena** [comment]
Hehe damn the same thing happened to me now too and I can't log in back to my own account either ;) have to have a look at the code.

**Comment by jeena** [comment]
Damn it was just a typo, I wrote profile_url.startsWith("https:((") insted of https:// I will upload a new version shortly just to fix that.
