### ISSUE TITLE
Add Fullscreen mode

### ISSUE THREAD

**Issue by jeena** [jeena/Bungloo#6]
Fullscreen mode with both timeline and mentions in same window. Or maybe the timeline in several columns?

**Comment by ghost** [comment]
some reasons to use in fullscreen would be:
1. distortion-free space, just one big field for writing statuses, and dimmed-out control elements like send button, permissions and such. very zen/whiteroom-ish
2. follow the timeline and/or mentions (and/or serch results) in realtime, again just one big message and some semi-visible controls
3. the "screensaver", timeline/mentions/search/favs floating from side to side in elegant manner )

**Comment by jeena** [comment]
Sadly this is too much work for now. Perhaps later when I make a complete rewrite or something.
