### ISSUE TITLE
try to unshorten any link by looking for 301/302 status-codes

### ISSUE THREAD

**Issue by ghost** [jeena/Bungloo#62]
for example there are at least 20 somewhat  popular shorteners, and listing each and every one of them in the code with api keys is not a rational way.

https://github.com/jeena/Tentia/blob/master/WebKit/scripts/helper/Core.js#L271

Much smarter would be requesting `HEAD` of any link and looking for 301/302 redirections, i suppose.

**Comment by jeena** [comment]
hehe omg the first twitter I tested had 4 redirects, but I think you're right head-requests make much more sense here.

**Comment by jeena** [comment]
I find that due to the length of 256 chars almost nobody posts shortened links.
