### ISSUE TITLE
support for tent:// url scheme links

### ISSUE THREAD

**Issue by ghost** [jeena/Bungloo#63]
well, at least mark them as "links"

https://github.com/jeena/Tentia/blob/master/WebKit/scripts/helper/Core.js#L411

also email links, prbly

**Comment by ghost** [comment]
rel: why not use http://medialize.github.com/URI.js/docs.html#static-withinString for links marking

**Comment by jeena** [comment]
Have a look at the whole code, the function you are looking at is the callback for URI.withinString.

**Comment by ghost** [comment]
hm, yeah, i missed it, my bad.

**Comment by jeena** [comment]
The tent:// scheme is not defined yet so I will not implement it yet.
