### ISSUE TITLE
Missing previous posts in Conversation view

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#65]
In the Conversation view for https://mompracem.tent.is/nh2jrg the previous posts are not loaded.
The direct parent is https://rcs.tent.is/posts/oxov7q .
TentStatus and Zelten correctly show the parent post.
I follow everybody mentioned except https://sikkdays.tent.is/ .

**Comment by jeena** [comment]
Tentia only shows the public ones because I wasn't able to get the thing via /followings working.

**Comment by poweruser82** [comment]
Isn't it public? I'm not mentioned in it and it shows in my timeline.
In the Conversation view for https://rcs.tent.is/posts/oxov7q the https://mompracem.tent.is/nh2jrg reply appears, but the previous posts are not loaded.

**Comment by jeena** [comment]
Ok it is a little bit more complicated. If you click on a post to show the conversation view then there are 2 things that happen. 
1. Tentia has a look at the first mention in the mentions array and if there is a post id then it loads this id from the server of the entity, it only gets the public posts, so if the post was not public it will not be able to show it. Tentia does it recursively for every such public post so it climbs up back in time until there is no parent post.
2. Tentia queries your server for future posts which mention the post you just opened. This shows all the posts which the post you opened is a parent of, and there you get non-public posts too. It does that also recursively until it finds only posts without children.

When I open https://mompracem.tent.is/nh2jrg I only see the header but no post so I assume it is a private post?

**Comment by riccard0** [comment]
I don’t see https://mompracem.tent.is/nh2jrg
But I do see https://mompracem.tent.is/posts/nh2jrg

**Comment by jeena** [comment]
Ok, I will have to check this in the evening when i'm done with my work.

**Comment by poweruser82** [comment]
I tweaked the URL from Zelten. I don't know what the right syntax to refer posts is. The one from TentStatus is probably better.

**Comment by jeena** [comment]
Internally the urls are different, it was said that to get a status post from a person you follow you have to do:

`api_root/followings/persons_api_root/posts/id`

to get your own post:

`api_root/posts/id`

to get a persons post who you not follow:

`persons_api_root/posts/id`

but sadly the first one doesn't work for me, I always get the `500 Internal Server Error`
