### ISSUE TITLE
Move Mentions and Timeline from File to Window menu item

### ISSUE THREAD

**Issue by jeena** [jeena/Bungloo#7]

**Comment by jeena** [comment]
If I move them to the Window menu item then when you close the Window (Cmd+w) they dissapear from the menu and you can't open the window anymore. So I think it is ok to have them in File for now.

**Comment by poweruser82** [comment]
Take a look to Messages application. It has items (Messages and Friends) in the Window menu that are there independently from the open windows.

**Comment by jeena** [comment]
Hm ok, I will have another look at it.

**Comment by tjreo** [comment]
+1. I agree that they belong in their own section of the Window menu.

**Comment by riccard0** [comment]
I said the same some time ago… So it’s a +1 from me too.

**Comment by jeena** [comment]
If anyone has some information on how to do it I would appreciate if you guys told me because if I just move them to the Windows menu then when you close the window some magic happens and you never can open it again.

**Comment by riccard0** [comment]
Looking at applications I use regularly, the most apt comparison would be mail.app. There the main window is in the Window menu (and is triggered by clicking the icon on the Dock), while new message is in the File menu. How to obtain it in Xcode, however, is way far out of my area of expertise.

**Comment by poweruser82** [comment]
My cocoa is very very rusty. You should unbind the menu item from the window management. Menu items should just toggle the correspondent window's visibility.

**Comment by jeena** [comment]
The problem is that I want to have the window management there because there are other windows there which could not show up anywhere otherwise.

**Comment by poweruser82** [comment]
I'm taking Messages as reference. It has _singleton_ windows (the unified or separated buddy list, messages, tranfers, contacts) and multiple instance windows (each conversation open in a separate window).
The Window menu has two section:
- the top one hosts the _singleton_ windows without any mark to indicate if they are open or active
- the bottom one with just the multiple instance windows with a mark to indicate the active window

**Comment by jeena** [comment]
Ah hm, this got me an idea, I read somewhere that you could say to a window that it should not act like a window which shows up in the Windows menu, I will test that.

**Comment by jeena** [comment]
Omg we all together are geniuses :D it worked! This will be in the next version ;)
