### ISSUE TITLE
Tentia crashes after a few minutes of adding location to a post.

### ISSUE THREAD

**Issue by arturovm** [jeena/Bungloo#73]
The first few lines of the crash log might provide some insight. It sounds like it's an object being released too early:

> Interval Since Last Report:          553051 sec
> Crashes Since Last Report:           2
> Per-App Interval Since Last Report:  1648 sec
> Per-App Crashes Since Last Report:   1
> Anonymous UUID:                      9C9E0A16-4679-4B29-AAB8-602118D694E0
> 
> Crashed Thread:  0  Dispatch queue: com.apple.main-thread
> 
> Exception Type:  EXC_BAD_ACCESS (SIGSEGV)
> Exception Codes: 0x000000000000000d, 0x0000000000000000
> 
> VM Regions Near 0:
> --> 
>     __TEXT                 0000000100000000-000000010000b000 [   44K] r-x/rwx SM=COW  /Applications/Tentia.app/Contents/MacOS/Tentia
> 
> Application Specific Information:
> objc_msgSend() selector name: respondsToSelector:
> objc[4321]: garbage collection is OFF
> 
> Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
> 0   libobjc.A.dylib                   0x00007fff89741150 objc_msgSend_vtable5 + 16
> 1   com.apple.corelocation            0x00007fff89145bf6 -[CLLocationManager onClientEventAuthStatus:] + 306
> 2   com.apple.corelocation            0x00007fff8913f459 CLClientInvokeCallback(__CLClient_, CLClientEvent, __CFDictionary const_) + 83
> 3   com.apple.corelocation            0x00007fff891412ce CLClientSendCachedRequests(__CLClient_) + 183
> 4   com.apple.corelocation            0x00007fff89140f90 CLClientHandleDaemonDataRegistration(__CLClient_, CLDaemonCommToClientRegistration const_, __CFDictionary const_, unsigned int) + 1065
> 5   com.apple.corelocation            0x00007fff89141489 CLClientRegister(__CLClient_, unsigned char) + 405
> 6   com.apple.corelocation            0x00007fff891411a6 CLClientHandleDaemonInvalidation(__CFMachPort_, void*) + 460
> 7   com.apple.CoreFoundation          0x00007fff8923afe1 ____CFMachPortChecker_block_invoke_1 + 33
> 8   libdispatch.dylib                 0x00007fff89940a82 _dispatch_call_block_and_release + 18
> 9   libdispatch.dylib                 0x00007fff899428f2 _dispatch_main_queue_callback_4CF + 308
> 10  com.apple.CoreFoundation          0x00007fff891e6e7c __CFRunLoopRun + 1724
> 11  com.apple.CoreFoundation          0x00007fff891e6486 CFRunLoopRunSpecific + 230
> 12  com.apple.HIToolbox               0x00007fff90aa52bf RunCurrentEventLoopInMode + 277
> 13  com.apple.HIToolbox               0x00007fff90aac56d ReceiveNextEventCommon + 355
> 14  com.apple.HIToolbox               0x00007fff90aac3fa BlockUntilNextEventMatchingListInMode + 62
> 15  com.apple.AppKit                  0x00007fff876ae779 _DPSNextEvent + 659
> 16  com.apple.AppKit                  0x00007fff876ae07d -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 135
> 17  com.apple.AppKit                  0x00007fff876aa9b9 -[NSApplication run] + 470
> 18  com.apple.AppKit                  0x00007fff87926eac NSApplicationMain + 867
> 19  nu.jabs.apps.tentia               0x0000000100001a14 start + 52

**Comment by jeena** [comment]
Somehow this has fixed itself, I can't reproduce it anymore.
