### ISSUE TITLE
Duplicated post in conversation view

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#77]
In the conversation view for the post `tent://jeena.net/posts/un94rs` the post `tent://tjreo.tent.is/posts/iyox5h` appears twice. I suppose because there are two distinct replies to it.
Also the ids of the two li tags are different. The first one has the post id, the second one an unknown `datlxb`.

**Comment by jeena** [comment]
Did this happen later again or was it just a one time weirdness perhaps even from the server or something?

**Comment by poweruser82** [comment]
I don't know I can go back to find that conversation.
I don't think I found the problem in recent conversations.

**Comment by jeena** [comment]
Ok then I think it was just some random weirdness and I will close this issue, feel free to reopen it if you see this happening again.

**Comment by poweruser82** [comment]
It happened again:
![Schermata 2013-01-10 alle 17 44 23](https://f.cloud.github.com/assets/325193/57373/26522aa6-5b45-11e2-98b6-3468a5425c57.png)

**Comment by jeena** [comment]
Hm interesting, I've never seen something like that happening.
