### ISSUE TITLE
Reposts should mention the original post

### ISSUE THREAD

**Issue by graue** [jeena/Bungloo#85]
From the [post type docs](https://tent.io/docs/post-types#repost):

> The repost should also include a mention of the original post so that the publisher can see who is reposting her content.

Yet, Tentia doesn't appear to do this. An example post from 4 hours ago today:

```
$ curl -s https://poweruser.tent.is/tent/posts/x9v90c | python -mjson.tool
{
    "app": {
        "name": "Tentia", 
        "url": "http://jabs.nu/Tentia/"
    }, 
    ...
    "mentions": [], 
    ...
    "type": "https://tent.io/types/post/repost/v0.1.0", 
    "version": 1
}
```

**Comment by jeena** [comment]
Oh, I wasn't aware of the fact that it should mention the original post.
