### ISSUE TITLE
Deleted posts in Timeline and Notification view

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#86]
The last night I got a reply to a post of mine. I received the notification and the reply appeared in Timeline and Notifications view.
Few minutes later the authors deleted the reply because it was an error.
This morning (at least 4 hours later) the reply was still in timeline in Tentia and Bivy.me and I replied to it via Tentia.
15 hours later, the reply still appears in TentStatus timeline, but not in Tentia's one. However it is still visible in Tentia's Notification view.

**Comment by jeena** [comment]
This is true, the mentions view doesn't remove deleted stuff yet, I'll try to fix it.

**Comment by jeena** [comment]
It seems that the server doesn't send me any information about deleted posts if I add &mentioned_entity=... I will write a bug report for tentd.

**Comment by jeena** [comment]
This is the issue I made on tentd https://github.com/tent/tentd/issues/70

**Comment by jeena** [comment]
Ok it was actually not a issue in the server but just me who misunderstood the protocol.
