### ISSUE TITLE
Deleted own post in Timeline

### ISSUE THREAD

**Issue by poweruser82** [jeena/Bungloo#88]
Publish a post and then delete it. It remains in the timeline until you restart Tentia.

**Comment by jeena** [comment]
Hm it doesn't for me, do you see something in the Console.app log?

**Comment by poweruser82** [comment]
It's empty :(

**Comment by jeena** [comment]
It is happening for me now too :-/

**Comment by jeena** [comment]
It seems that this is a bug in tentd because this is happening to TentStatus too: https://github.com/tent/tentd/issues/58

**Comment by jeena** [comment]
They fixed the issue in tentd
