### ISSUE TITLE
[Linux] "Reply" to your own post adds your entity to the mentions

### ISSUE THREAD

**Issue by peakwinter** [jeena/Bungloo#95]
Clicking "Reply" on your own post adds your own entity in the new post as a mention.

**Comment by jeena** [comment]
Yes that is like it is working, what would you expect it to do instead?

**Comment by peakwinter** [comment]
Ahh OK I wasn't sure if it was planned that way or not. When you do the same thing in TentStatus, it adds other people's entities EXCEPT your own. Because in most circumstances I'd wager you don't care about mentioning yourself in your own post :)

**Comment by jeena** [comment]
Hm, the thing is that I need to add it to the mentions array so I can put in the post_id to the original post so it shows up in the conversation view too. So even if I would remove the ^entity from the text, it will still be in the mentions array, and it is if you remove the ^entity manually. So I thought it would be less magic if I add it.
