### ISSUE TITLE
[Linux] App icon and desktop launching

### ISSUE THREAD

**Issue by bnb** [jeena/Bungloo#97]
The application needs to be able to be launched from the desktop/applications menu to be called a full application. I assume we can use the Tent icon present in the main wiki page and on the "Enter your entity" page for the application icon. I want to be able to launch the application from my desktop environment--I'm not even sure if this is possible with the way the application is currently set up, but I thought I would just point it out.

**Comment by jeena** [comment]
Yes that is the next step actually. Sadly I have no idea how to do it. When I started developing the Linux version I asked the guys on freenode#qt if when I program the app like I did (python + resources) if I will be able to distribute it in some way. They said "yeah no problem, just start writing it you can figure that out later" and so I did.

**Comment by jeena** [comment]
With the new icon and deb this is resolved.
